---
prometheus_cloudwatch_exporter_version: 0.6.0
prometheus_cloudwatch_exporter_server: localhost
prometheus_cloudwatch_exporter_port: 9106

prometheus_cloudwatch_exporter_metrics: |
  - aws_namespace: AWS/RDS
    aws_metric_name: UnealthyHostCount
    aws_tag_select:
      tag_selections:
        automation_environment: ["{{ env }}"]
        automation_project: ["{{ project }}"]
        Name: ["{{ env }}-cdh-instance_rds_instance"]
    set_timestamp: false

# Other vars are re-used from the main prometheus role including
# prometheus_artifact_bucket
# prometheus_exporters_common_root_dir
# prometheus_exporters_common_dist_dir
# prometheus_exporters_common_group
# prometheus_exporters_common_user
