---

- name: reenable node exporter service
  systemd:
    name: "prometheus-node-exporter.service"
    daemon_reload: true
    enabled: true

- name: reinit node exporter
  command: initctl reload-configuration

- name: restart node exporter
  service:
    name: prometheus-node-exporter
    state: restarted
