---

- name: Create our jmx exporter directory
  file:
    state: directory
    path: "{{ prometheus_exporters_common_dist_dir }}/jmx_exporter"

- name: Download our package
  aws_s3:
    bucket: "{{ prometheus_artifact_bucket }}"
    object: "/jar/jmx_prometheus_httpserver-{{ prometheus_jmx_version }}.jar"
    dest: "{{ prometheus_exporters_common_dist_dir }}/jmx_exporter/jmx_prometheus_httpserver-{{ prometheus_jmx_version }}.jar"
    mode: get
    overwrite: different

- name: update group and owner for files
  file:
    path: "{{ prometheus_exporters_common_dist_dir }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
  changed_when: false

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/jmx_exporter/jmx_prometheus_httpserver-{{ prometheus_jmx_version }}.jar"
    path: "{{ prometheus_exporters_common_root_dir }}/jmx_prometheus_current"
    state: link

- name: Create our config file
  template:
    src: "{{ role_path }}/templates/prometheus_jmx.yml.j2"
    dest: "{{ prometheus_exporters_common_dist_dir }}/jmx_exporter/config.yml"
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
    mode: '0644'
    remote_src: "{{ prometheus_jmx_remote_src | default(true) }}"

- name: create startup script for our service
  template:
    src: stats.j2
    dest: "{{ prometheus_exporters_common_dist_dir }}/jmx_exporter/stats"
    mode: 0755
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
    remote_src: "{{ prometheus_jmx_remote_src | default(true) }}"

- name: configure the service config
  template:
    src: prometheus-jmx-exporter.service.j2
    dest: /etc/systemd/system/prometheus-jmx-exporter.service
    owner: root
    group: root
    mode: 0644
    remote_src: "{{ prometheus_jmx_remote_src | default(true) }}"

- meta: flush_handlers

- name: configure the service
  systemd:
    name: "prometheus-jmx-exporter"
    enabled: true
    state: started
