---

- name: reenable graphite exporter service
  systemd:
    name: "prometheus-graphite-exporter.service"
    daemon_reload: true
    enabled: true

- name: reinit graphite exporter
  command: initctl reload-configuration

- name: restart graphite exporter
  service:
    name: prometheus-graphite-exporter
    state: restarted
