---

- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install pre-requisites for environment
      apt:
        name:
          - python-pip
          - curl
        state: present
