---

# Defaults from galaxy role and meta dependencies
prometheus_node_exporter_config_flags:
  'web.listen-address': '0.0.0.0:9100'
  'log.level': 'info'

prometheus_node_exporter_enabled_collectors:
  - conntrack
  - diskstats
  - entropy
  - filefd
  - filesystem
  - loadavg
  - mdadm
  - meminfo
  - netdev
  - netstat
  - stat
  - systemd
  - textfile
  - time
  - vmstat
