---

- name: reenable hdfs stats exporter service
  systemd:
    name: "prometheus-hdfs-stats-exporter.service"
    daemon_reload: true
    enabled: true

- name: reinit hdfs stats exporter
  command: initctl reload-configuration

- name: restart hdfs stats exporter
  service:
    name: prometheus-hdfs-stats-exporter
    state: restarted
