---

ansible:
  config_file: ${PROJECT_ROOT}/ansible.cfg

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: prometheus_node_exporter_xenial
    image: jrei/systemd-ubuntu:16.04
    override_command: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: eu-west-1
  - name: prometheus_node_exporter_centos
    image: centos:7
    override_command: true
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: eu-west-1

provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: ${PROJECT_ROOT}/library/
    ANSIBLE_FILTER_PLUGINS: ${PROJECT_ROOT}/filter_plugins/
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
